### ISSUE TITLE
GL ES 2.0 error

### ISSUE THREAD

**Issue by z-lumley** [kreshuklab/plant-seg#309]
Hi, I have installed PlantSeg using the instructions.

I ran into the same problem as _adkrishnan_ in issue #274 and used their solution to install bioimageio.core

That solved that issue, however when attempting to run `plantseg --napari` or `plantseg --gui` I get the following error:

```bash
plantseg --napari
You are using the latest version of PlantSeg: 1.8.1.
WARNING: Could not load OpenGL library.
Traceback (most recent call last):
  File "/home/zac/micromamba/envs/plant-seg/bin/plantseg", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/plantseg/run_plantseg.py", line 79, in main
    launch_napari()
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/plantseg/run_plantseg.py", line 30, in launch_napari
    from plantseg.viewer.viewer import run_viewer
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/plantseg/viewer/viewer.py", line 3, in <module>
    from plantseg.viewer.containers import get_proofreading
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/plantseg/viewer/containers.py", line 6, in <module>
    from plantseg.viewer.widget.dataprocessing import widget_cropping, widget_merge_layers
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/plantseg/viewer/widget/dataprocessing.py", line 9, in <module>
    from napari.layers import Image, Labels, Shapes, Layer
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/napari/layers/__init__.py", line 10, in <module>
    from napari.layers.base import Layer
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/napari/layers/base/__init__.py", line 1, in <module>
    from napari.layers.base._base_constants import ActionType
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/napari/layers/base/_base_constants.py", line 4, in <module>
    from napari.utils.misc import StringEnum
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/napari/utils/__init__.py", line 3, in <module>
    from napari.utils.colormaps.colormap import (
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/napari/utils/colormaps/__init__.py", line 2, in <module>
    from napari.utils.colormaps.colormap import (
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/napari/utils/colormaps/colormap.py", line 19, in <module>
    from napari.utils.color import ColorArray
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/napari/utils/color.py", line 8, in <module>
    from napari.utils.colormaps.standardize_color import transform_color
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/napari/utils/colormaps/standardize_color.py", line 28, in <module>
    from vispy.color import ColorArray, get_color_dict, get_color_names
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/vispy/color/__init__.py", line 12, in <module>
    from .colormap import (Colormap, BaseColormap,  # noqa
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/vispy/color/colormap.py", line 14, in <module>
    import vispy.gloo
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/vispy/gloo/__init__.py", line 47, in <module>
    from . import gl  # noqa
    ^^^^^^^^^^^^^^^^
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/vispy/gloo/gl/__init__.py", line 230, in <module>
    from . import es2 as default_backend  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zac/micromamba/envs/plant-seg/lib/python3.12/site-packages/vispy/gloo/gl/es2.py", line 48, in <module>
    raise OSError('GL ES 2.0 library not found')
OSError: GL ES 2.0 library not found
```

Any advice or suggestions would be appreciated!

**Comment by qin-yu** [comment]
Hi @z-lumley thanks for reporting. Are you using a Mac?

**Comment by z-lumley** [comment]
Hi @qin-yu, I'm using Ubuntu 22.04 through WSL

**Comment by z-lumley** [comment]
Thanks for all the help, @qin-yu. I never figured out the issue with WSL unfortunately -- I guess it must be some issue with my WSL or the way I installed, as I am quite new to all this. However, trying the Miniforge Windows installation route did work, after following the solution in #344. I now have PlantSeg running. Thanks 😄
