### ISSUE TITLE
Possible issues in 1.8.1

### ISSUE THREAD

**Issue by PauCasanova** [kreshuklab/plant-seg#342]
Good afternoon,

I am running the 1.8.1 version of plantseg on a linux Mint 22 machine.
Everything works as intended but in some case I get the following error:
```
2024-10-01 17:44:23,683 [MainThread] INFO PlantSeg - Computing segmentation with dtWS...
Traceback (most recent call last):
  File "/home/pcasanova/anaconda3/envs/plant-seg/bin/plantseg", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pcasanova/anaconda3/envs/plant-seg/lib/python3.12/site-packages/plantseg/run_plantseg.py", line 83, in main
    process_config(args.config)
  File "/home/pcasanova/anaconda3/envs/plant-seg/lib/python3.12/site-packages/plantseg/run_plantseg.py", line 64, in process_config
    raw2seg(config)
  File "/home/pcasanova/anaconda3/envs/plant-seg/lib/python3.12/site-packages/plantseg/pipeline/raw2seg.py", line 149, in raw2seg
    output_paths = pipeline_step()
                   ^^^^^^^^^^^^^^^
  File "/home/pcasanova/anaconda3/envs/plant-seg/lib/python3.12/site-packages/plantseg/pipeline/steps.py", line 70, in __call__
    return [self.read_process_write(input_path) for input_path in self.input_paths]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcasanova/anaconda3/envs/plant-seg/lib/python3.12/site-packages/plantseg/pipeline/steps.py", line 88, in read_process_write
    output_data = self.process(input_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcasanova/anaconda3/envs/plant-seg/lib/python3.12/site-packages/plantseg/segmentation/gasp.py", line 84, in process
    ws = self.dt_watershed(pmaps)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcasanova/anaconda3/envs/plant-seg/lib/python3.12/site-packages/plantseg/segmentation/functional/segmentation.py", line 73, in dt_watershed
    segmentation, _ = distance_transform_watershed(boundary_pmaps, **ws_kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcasanova/anaconda3/envs/plant-seg/lib/python3.12/site-packages/elf/segmentation/watershed.py", line 138, in distance_transform_watershed
    seeds = compute_maxima(dt, marker=np.nan, allowAtBorder=True, allowPlateaus=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 
Invariant violation!
connected components: Need more labels than can be represented in the destination type.
(/home/conda/feedstock_root/build_artifacts/libvigra_1725360696982/work/include/vigra/union_find.hxx:283)
```
I have no idea if its an issue from my side but I was wondering if somebody else had this issue before

And not related but also a bit bothersome is that in regular monitors (1920x1080) the gui screem does not work because the run button does not fit. I run it with the config files so it does not affet me but I thought that it was worth mentioning.
![image](https://github.com/user-attachments/assets/33e7f38c-9d2f-4e92-a368-bf4924d8488c)

**Comment by lorenzocerrone** [comment]
Hi,

Regarding your first question, yes, we have seen a similar issue in the past, but we could never reproduce it on a different machine. 
It would be great if you could share/or privately send me the problematic image. Unfortunately, so far, we have never been able to pinpoint the issue. 

Regarding your second question, you should be able to resolve this issue by adjusting the font size in the edit menu. The plantseg gui has been removed from plantsegv2, but we are diligently working on a new one with improved support for different monitors. The new gui is expected to be ready in a few weeks.

**Comment by qin-yu** [comment]
Hey @PauCasanova do you still need help for the first part of this issue `connected components: Need more labels than can be represented in the destination type.`?

For the second part "in regular monitors (1920x1080) the gui screen does not work", please refer to the [troubleshooting](https://kreshuklab.github.io/plant-seg/chapters/getting_started/troubleshooting/#font-size-problems-in-gui) and issue #241

**Comment by qin-yu** [comment]
I just noticed that this issue is related to:

- #166

**Comment by qin-yu** [comment]
Hey @PauCasanova we would really appreciate if you can send us the image for debugging.

**Comment by PauCasanova** [comment]
Hi there,

I already sent an image to Lorenzo Cerrone on the [image: Attachments]3 Oct
2024, 12:58.
But here you have it again:
https://drive.google.com/file/d/10b44hT2ZnhB-vk4p4rZX__es8PqCg7Om/view?usp=sharing

Best,
Pau

**Comment by PauCasanova** [comment]
Hi there,
How is this going ?

Best,
Pau

**Comment by KRiedmiller** [comment]
Are you getting this issue repeatedly/consistently? Please add me to the share above (I've sent a request) , so I can try to reproduce the issue.

**Comment by PauCasanova** [comment]
Yes, I moved out of that dataset, but I still keep having the same issue with some other images.

I have now 5 nuclei segmentations with the same issue, 
This is an example of my .yaml
```
cnn_postprocessing:
  channel: 1
  factor: &id001
  - 0.7426701570680628
  - 0.3664739884393064
  - 0.3664739884393064
  key: null
  order: 2
  state: true
  tiff: true
cnn_prediction:
  channel: null
  device: cuda
  key: null
  model_name: PlantSeg_3Dnuc_platinum
  model_update: false
  num_workers: 8
  patch:
  - 100
  - 280
  - 280
  patch_halo:
  - 20
  - 56
  - 56
  state: true
  stride_ratio: 0.5
path: /netscratch/dep_coupland/grp_formosa/pcasanova/CLV1/NucSeg/Side_clv1_13LDs_SAM2_nuclei_Z0.382_X0.346_Y0.346_Sz365_Sx800_Sy800.tif
preprocessing:
  channel: null
  crop_volume: '[:,:,:]'
  factor:
  - 1.3464927740571027
  - 2.728706624605678
  - 2.728706624605678
  filter:
    filter_param: 1.0
    state: false
    type: gaussian
  key: null
  order: 2
  save_directory: PreProcessing
  state: true
segmentation:
  beta: 0.5
  channel: 1
  key: predictions
  name: GASP
  post_minsize: 100
  run_ws: true
  save_directory: GASP
  state: true
  ws_2D: false
  ws_minsize: 50
  ws_sigma: 2.0
  ws_threshold: 0.4
  ws_w_sigma: 0
segmentation_postprocessing:
  channel: null
  factor: *id001
  key: null
  order: 0
  save_raw: false
  state: true
  tiff: true
```
and the image is 
https://drive.google.com/file/d/1bD9hTns45d5jDLoDmyE_tB-huI-xbMzd/view?usp=drive_link

Best,
Pau

**Comment by KRiedmiller** [comment]
This is quite out-of-date and I can't reproduce it. Closing for now, if the issue occurs with a recent version, please open another issue.
