### ISSUE TITLE
 DLL load failed while importing _nifty: The specified module could not be found.

### ISSUE THREAD

**Issue by Giannisbiol** [kreshuklab/plant-seg#344]
Hi,

 I just installed the latest version (2.0.0a3) but I got an error and napari gui doesnt load. 

please see below:

```bash
(plseg) C:\Users\user1>plantseg --napari
INFO: P [MainThread] 2024-10-02 11:22:22,631 plantseg - Logger configured at initialisation. PlantSeg logger name: plantseg
INFO: P [MainThread] 2024-10-02 11:22:23,267 plantseg.utils - You are using the latest version of PlantSeg: 2.0.0a3.
Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Scripts\plantseg-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Lib\site-packages\plantseg\run_plantseg.py", line 74, in main
    launch_napari()
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Lib\site-packages\plantseg\run_plantseg.py", line 43, in launch_napari
    from plantseg.viewer_napari.viewer import run_viewer
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Lib\site-packages\plantseg\viewer_napari\viewer.py", line 4, in <module>
    from plantseg.viewer_napari.containers import (
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Lib\site-packages\plantseg\viewer_napari\containers.py", line 3, in <module>
    from plantseg.viewer_napari.widgets import (
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Lib\site-packages\plantseg\viewer_napari\widgets\__init__.py", line 1, in <module>
    from plantseg.viewer_napari.widgets.dataprocessing import (
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Lib\site-packages\plantseg\viewer_napari\widgets\dataprocessing.py", line 9, in <module>
    from plantseg.tasks.dataprocessing_tasks import (
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Lib\site-packages\plantseg\tasks\__init__.py", line 13, in <module>
    module = importlib.import_module(f'{__name__}.{module_name}')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Lib\site-packages\plantseg\tasks\segmentation_tasks.py", line 5, in <module>
    from plantseg.functionals.segmentation import (
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Lib\site-packages\plantseg\functionals\segmentation\__init__.py", line 1, in <module>
    from plantseg.functionals.segmentation.segmentation import (
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Lib\site-packages\plantseg\functionals\segmentation\segmentation.py", line 3, in <module>
    import nifty
  File "C:\Users\user1\AppData\Local\miniforge3\envs\plseg\Lib\site-packages\nifty\__init__.py", line 4, in <module>
    from ._nifty import *
ImportError: DLL load failed while importing _nifty: The specified module could not be found.
```

**Comment by LoicKouokam** [comment]
Hello ,

I also have the same problem !

**Comment by lorenzocerrone** [comment]
Hi all,

I have not yet tried to install plantseg on Windows, I will write back as soon as I test it.

**Comment by anwai98** [comment]
Hi all,

I stumbled upon this and would like to share feedback for a similar issue we've heard on this topic.

In short, the (latest) build version 5 for nifty seems to not work on Windows at the moment.
The current workaround to avoid this issue is to use the previous build version (4), i.e. supported for python 3.8, 3.9, 3.10 and 3.11 - using a wildcard for the build version.

Hence, one has to make sure to install `nifty` in their environment supporting aforementioned python versions using:
```bash
$ mamba install -c conda-forge nifty=1.2.1=*_4
```

Hope that helps! :)

**Comment by lorenzocerrone** [comment]
Awesome, thanks for the feedback @anwai98!

**Comment by lorenzocerrone** [comment]
I was not able to reproduce the issue on my windows machine, but with the updated installation docs the installation should work in any case. Please reopen this issue if the problem persists.

**Comment by anwai98** [comment]
Hi @lorenzocerrone,

Just to keep you posted, `nifty` should be now fixed in `conda-forge` for Windows users (all thanks to @constantinpape)!

I think you can release the pin for the wildcard for specific build from the docs, or anywhere else! :)
